name: Publish release to NuGet
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ github.token }}

      - name: Publish NuGet Package
        id: publish_nuget
        shell: pwsh
        run: |
          dotnet restore
          dotnet nuget list source
          $version = (Select-String -Pattern "^\s*<Version>(.*)<\/Version>\s*$" -Path .\TestCore.csproj).Matches[0].Groups[1].Captures[0].Value
          dotnet pack --configuration Release
          dotnet nuget push ((Get-ChildItem ".\bin\Release\*.nupkg")[0].FullName) --api-key "${{ github.token }}" --source "github"